# Hands-on 3

**Reshaping Your Data**  

For this project you will take data in one format and reshape into a more optimal format for analysis.  We'll assume the analysis will be done in another tool.  OpenRefine can export data in multiple formats after the user has applied the necessary structure.  For this lab, We will continue exploring how OpenRefine can import various data formats.  This time we'll import Excel. I encourage you to download and first look at the raw Excel data first in Excel so you can see how you have changed the data.  

**Goals**  
1. Import Excel worksheets  
2. Faceting & Filtering for select data cleaning  
3. Transforming:  Adding columns and using fill-down to fill in data  


Basically you are making minor changes to the shape of the data by transforming some horizontal data into a more vertical format.  This is a common data wrangling need.


The data, “Salary.xslx”, are NBA salary data.  

## Ingest Excel data  

1. Open  Data  
    * **Create Project  > Web Addresses (URLs) >** `https://github.com/libjohn/openrefine/raw/master/data/salary.xlsx`
    * Next >> 
    * You many want to give your project a pretty title
    * Create Project >>
    * Parse data as 
        1. Worksheets to Import: **Check** "2013-2014 666 rows" & **UnCheck** "2014-2015 599 rows"  
        2. **UnCheck** "Store blank rows" 
            + Notice lines 20 & 22 disappear  
        3. **UnCheck** "Parse Next" 1 lines as column headers 
            + Notice the "Atlanta Hawks" are no longer the column header for the first column  
    * Project name = `salary data` > Create Project  
2. Rename Columns: "Player", "Salary", "Notes"  (Column Header > Edit Column > Rename this column)  
3. Show as: rows to '25' (notice row 21)

## Facets
4. Remove all rows where '----' exist in the Player column  
    + **Player > Facet > Text Facet** > 
        * Sort by: count > click: '----' :  
        * You should now have 29 matching rows that begin '----'  
    + All > Edit rows > Remove all matching rows  
    + Click:  **Remove All** in the **Facet/Filter** sidebar  
    
> Notice: in the next step, team names precede each team roster and are followed by two blank cells in the same row.  Scroll through the screens (Click "next >") a few times; return to the first screen  

5. Make a column for team name and fill it.  
    + Isolate team-name rows using a facet on the blank cells in the Salary column  
        1. Salary > Facet > Customized facets > Facet by blank 
            + Why do you think **this doesn’t work**? Those cells are actually filled with an invisible space (\s).  They’re not actually blank and only appear blank. So,  **regular expressions** to the rescue!  
        2. Close the facet  
    + Salary > Text filter > check "regular expression" > `^\s`  
        + `\s` means “a space”; `^` means “must begin the line”  
    + **Mouseover** the the "Cleveland Cavaliers" **Salary cell**:  
        + edit > highlight all the text EXCEPT the first space:  "Tot   $66,611,520" > <<cut to clipboard>> > Apply  
        + BE SURE to leave a blank space where the Salary data was  
    + Edit the individual Notes cell for the "Cleveland Cavaliers" cell:  
        + edit > paste from clipboard "Tot $66,611,520" > Apply  
        + This time you do not need a leading blank space  
        
## Text Filter  

6. Add the team name as a new column for each player then remove team name from the Player Column  
    1. Player > Edit column > Add column based on this column ... > New column name = `Team` > OK  
    2. Remove All facets  
    3. Team > Edit cells > Fill down  
    4. Salary > Text filter > check "regular expression" > `^\s`
    5. All > Edit rows > Remove all matching rows  
    6. Close (or "X out") the Salary text filter

# slide 32

# Hands-on 4
## Dates are weird!
## Analyzing differences