---
title: "Facet and Cluster"
output: html_document
---


## Facets & Cluster


### Goal 1:  Create a facet of authorized work.  Cluster & Merge types of authorized work.

1. *How many rows are in this dataset?* (answers facet_answers file)
2. Slide the bottom column navigation bar to the right
    + find the authorized_work column 
    + click the column header:  **authorized_work > Facet > Text facet**
3. *How many facets are there?*
4. In the Facet box, click “count”.  *What is the 4th most popular type of authorized work?  How permits are authorized?*
5. Find spelling clusters by clicking the “Cluster” button in the facet box
6. Using the “Select All” button “Merge Selected & Re-Cluster” all terms 
by the defaults (Method = “key collision” ; Keying Function = “fingerprint”)
7. Do the same for the “ngram-fingerprint” Keying Function, then close the 
Cluster & Edit dialog box
8. *How many SCREEN PORCH facets now exist?*


### Goal 2:  Create compound facets
1. Select the DECK Facet.  *How many matching rows match the Deck Facet?*
2. Select the SCREEN PORCH facet combined with the DECK Facet.  *Now how many matching rows exist?*
3. On the “land_use_code” column, make a text facet and limit to 
“SINGLE FAMILY”
4. On the “county” column, make a text facet and limit to Durham County (DURH)
*How many “Single Family” homes got permits in Durham County for Screen Porches or Decks?  Is the authorized work for Screen Porches, Decks, or both?*
5. Click the “Remove All” button to remove all text facets.  *How many matching rows are in the dataset now?*