---
title: "fetch, scrape, & parse"
output: html_document
---

## Goal:  Fetch data from a remote server.  

We want to gather the FIPS code for a subset of the data.  The government server returns data in a JSON format so we’ll parse the data after we retrieve it. First we’ll subset our dataset for expediency.  This limits our waiting time during the workshop.


1. **issue_date > Facet > Custom text facet… **
    + expression = `value.slice(6,10)`
2. select the “2014” facet
3. **authorized_work > Facet > Text facet**
4. select the “3 SEASON ROOM” facet

You should now have 6 matching rows.  Next we’ll use Refine to gather data from another website.  Our Goal is to get the FIPS code for all counties. 

## API

Now let’s fetch the data from an [API](http://www.broadbandmap.gov/developer/) made available via the [National Broadband Map](http://www.broadbandmap.gov/). This API returns a FIPS code if we give it a county name (or in this case, even a partial county name.)


5. fetch JSON data from the National Broadband Map.  We’ll use the [API documentation for Geography by Name API](http://www.broadbandmap.gov/developer/api/census-api-by-geography-name) which returns Census geography for a geography name (e.g. Durham)  
    + The documentation informs us that the format of the url we want to construct is as follows:
http://www.broadbandmap.gov/broadbandmap/census/county/durh?format=json 
    + Notice the data values in the “county” column.  All we do is construct a URL which calls the value of the cells from each row of the “country” column
    + **county > Edit column > Add column by fetching URLs…**
    + New column name = `JSON data`
    + Throttle delay = `2000`
    + Expression = 
`http://www.broadbandmap.gov/broadbandmap/census/county/'+value+'?format=json`
    + OK

## Parse

Now parse the value of the JSON data “fips” element; call the “fips” key when traversing the “county” objects from the Results set.


6. **JSON data > Edit column > Add column based on this column ...**  
    * New column name = `FIPS Code`  
    * expression = `value.parseJson().Results.county[0].fips`  
    
    
## JSON

JSON is JavaScript Object Notation a data wrapper.  The API, in this case, returns the data in a JSON format.

The data are returned in in JSON format 

```{JSON}
{
  "status": "OK",  
  "responseTime": 14,  
  "message": [  ],  
  "Results": {  
    "county": [  
      {  
        "geographyType": "COUNTY2010",  
        "stateFips": "37",  
        "fips": "37063",  
        "name": "Durham"  
      }  
    ]  
  }  
}  
```
  
